### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by cheoAlejo** [ochorocho/gitdownload#6]
It looks like a good and useful plugin, however, I haven't been able to make it work. I have my repos locally in `/opt/redmine/repos`. The downloaded files are empty.
![2015-05-26 00_53_00-gitdownload plugin - plugins - configuration_ gitdownload plugin - delfin redmin](https://cloud.githubusercontent.com/assets/10518807/7806047/acca0814-0341-11e5-965c-b20be50d2d99.png)

**Comment by ochorocho** [comment]
Hey

GIT Remote URL is just to display a nice looking clone command like:
  git clone https://yourgit.com/git/repo_name/

Make sure you have set the correct git path in settings / repositories.
And check your production.log for error messages.

Gitdownload should get the repository from database as it is shown in Project -> Configuration -> Projectarchive

Thanks.

**Comment by cheoAlejo** [comment]
Hey, thanks for the answer. It was just a permissions problem in the folder `tmp`. It's working like a charm now. I found it very useful especially the **export specific changeset** feature.

Sorry for misunderstanding the `GIT Remote URL` setting, however, I dont see it displayed anywhere. I already set it and check the `Show repository URL` checkbox but I dont see it :(

**Comment by ochorocho** [comment]
Hey, glad to hear its working for you.

GIT Remote URL is only for setting the correct url to clone your git repository. It only enable you to copy a command to a working repo.
"Show repository URL" checkbox allows you to show or hide the clone command e.g. "git clone https://redmine.knallimall.org/git/hammercarousel/"

I hope is helps. :-)

Thanks for using gitdownload.

**Comment by cheoAlejo** [comment]
Mm, ok, understood ;-)
