### ISSUE TITLE
Include repo id in downloaded file name

### ISSUE THREAD

**Issue by cheoAlejo** [ochorocho/gitdownload#8]
Perhaps it could be handy if the name of the downloaded file includes the repository id, instead of the project name only. 

For instance, I have 5 repos associated to only one project and when I download any of them, they all have the same name :grimacing:.

![2015-06-09 11_33_20-_ - repo - g0 - delfin redmine](https://cloud.githubusercontent.com/assets/10518807/8063950/381c481c-0e9d-11e5-93cb-6a7bee80e7a9.png)

_Wished:_
![2015-06-09 11_48_17-escritorio](https://cloud.githubusercontent.com/assets/10518807/8063989/754c8c42-0e9d-11e5-9805-ded99ea2b4da.png)

**Comment by ochorocho** [comment]
hey ..

will do this after i merged your pull request. thanks. :-)

**Comment by cheoAlejo** [comment]
:v:

**Comment by ochorocho** [comment]
@cheoAlejo would you mind testing the changes? And sorry for the delay.

**Comment by cheoAlejo** [comment]
Tested !, works perfect. Thanks for the fix.

**Comment by ochorocho** [comment]
Thanks for testing
